version: '3.9'
services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started

  db:
    image: postgres
    environment:
      POSTGRES_DB: music_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d music_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A spotify worker --loglevel=info
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started

  beat:
    build: .
    command: celery -A spotify beat --loglevel=info
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_started
      redis:
        condition: service_started