# Generated by Django 4.2.23 on 2025-07-24 20:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.IntegerField(choices=[(0, 'ACTIVE'), (1, 'INACTIVE')], db_index=True, default=0)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('genre', models.IntegerField(choices=[(0, 'POP'), (1, 'ROCK'), (2, 'HIPHOP'), (3, 'JAZZ'), (4, 'CLASSICAL')], default=0)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('user_rating', models.FloatField(default=0.0)),
                ('social_shares', models.PositiveIntegerField(default=0)),
                ('geographic_popularity', models.JSONField(default=dict)),
                ('last_played', models.DateTimeField()),
                ('trending_score', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
