# Generated by Django 4.2.23 on 2025-07-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.IntegerField(choices=[(0, 'POP'), (1, 'ROCK'), (2, 'HIPHOP'), (3, 'JAZZ'), (4, 'CLASSICAL')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='trending_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
